export const FETCH_CAKES = 'FETCH_CAKES';
export const FETCH_CAKES_SUCCESS = 'FETCH_CAKES_SUCCESS';
export const FETCH_CAKES_FAILURE = 'FETCH_CAKES_FAILURE';

export const SEARCH_CAKES = 'SEARCH_CAKES';
